//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetManagement.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillDestination
    {
        public System.Guid Id { get; set; }
        public string BusinessName { get; set; }
        public string BusinessAddress { get; set; }
    }
}
